name: Golang Graduation Notification Hub Deployment

on:
  push:
    branches:
      - main
      - github-workflow
  workflow_dispatch:

env:
  IMAGE_NAME: seacloudserver/notification-hub
  CONTAINER_NAME: notification-hub
  PORT: 8089
  ENV_FILE_NAME: .env.notification
  AWS_REGION: ap-northeast-1  # Update this to your AWS region
  ECR_REPOSITORY: graduation-project # Update this to your ECR repository name

jobs:
  build_notification_hub:
    if: github.ref == 'refs/heads/main'
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Login to Amazon ECR
        id: ecr-login
        uses: aws-actions/amazon-ecr-login@v1
        with:
          region: ${{ env.AWS_REGION }}

      - name: Docker build and push
        run: |
          # Define the ECR repository URI
          repository_uri="${{ steps.ecr-login.outputs.registry }}/${{ env.ECR_REPOSITORY }}"
          
          # Build the Docker image
          docker build -t $repository_uri -f cmd/httpserver/Dockerfile .

          # Push the Docker image to ECR
          docker push $repository_uri
        env:
          AWS_REGION: ${{ env.AWS_REGION }}
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
